version: '3.8'

services:
  crawl4ai:
    image: unclecode/crawl4ai:0.7.6
    container_name: crawl4ai-server
    ports:
      - "11235:11235"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11235/health"]
      interval: 30s
      timeout: 10s
      retries: 3